services:
  # web:
  #   build: .
  #   ports:
  #     - "80:8000"
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   command: ["python", "app.py"]

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    user: postgres
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db
    #   POSTGRES_USER: stefan
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080